### ISSUE TITLE
CrackMe v3 remote license server is down

### ISSUE THREAD

**Issue by 0xmbe** [mrhery/CrackMe#3]
Link to https://license-crackme.tukul.app/v3/get-key.php is down. Looks like whole server can't be reached.

**Comment by Yoanndp** [comment]
Hello, I am not the owner of this repository, but as a workaround, you can use the Windows hosts file to remap the domain to your localhost server or use a custom DNS server

**Comment by 0xmbe** [comment]
> Hello, I am not the owner of this repository, but as a workaround, you can use the Windows hosts file to remap the domain to your localhost server or use a custom DNS server

I get:
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

I have routed address in hosts. Apache ssl is running. Installed my own cert.
I tried rebuilding the app and setting the connection directly to _http://127.0.0.1/v3/get-key.php_  and that works, but going to _https://license-crackme.tukul.app/v3/get-key.php_ doesnt work.

**Comment by mrhery** [comment]
Hi guys! Sorry for the delay. I have updated the code to read from the `localhost` instead of the remote host.

I have uploaded the `crackme-web` folder which is contains the simple `php` codes for the crackmev3, v4 and v5.

Just put the `crackme-web` folder directly to you webroot folder. In my case I use xampp stack, so the path will be: `c:/xampp/htdocs/crackme-web`.

Thank you guys for reminding me. I will keep update the crackme version in future.

**Comment by Yoanndp** [comment]
Nice to know @mrhery. I will probably submit a pull request soon to suggest the use of a docker-compose for the web part. It should be easier to use and maintain instead of using xampp.

**Comment by mrhery** [comment]
> Nice to know @mrhery. I will probably submit a pull request soon to suggest the use of a docker-compose for the web part. It should be easier to use and maintain instead of using xampp.

Ya sure can too. Thanks. I am closing this issue ok!
